stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
      - data/flats.csv
      - data/houses.csv
    outs:
      - data/raw.csv
    params:
      - data