stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
      - data/flats.csv
      - data/houses.csv
    params:
      - data.merged_data_path
      - data.raw_data_paths.flats
      - data.raw_data_paths.houses
    outs:
      - data/raw.csv

  data_cleaning:
    cmd: python src/data_cleaning.py
    deps:
      - src/data_cleaning.py
      - data/raw.csv
    params:
      - data.cleaned_data_path
      - cleaning.drop_columns
      - cleaning.rating_columns
      - cleaning.fillna_strategy
    outs:
      - data/cleaned.csv

  data_transformation:
    cmd: python src/data_transformation.py
    deps:
      - src/data_transformation.py
      - data/cleaned.csv
    params:
      - data.train_data_path
      - data.test_data_path
      - data.processed_data_path
      - data_split.test_size
      - data_split.random_state
      - features.selected_features
      - features.target_column
      - feature_engineering.age_mapping
      - feature_engineering.facing_mapping
      - feature_engineering.default_age_years
      - feature_engineering.default_facing_code
    outs:
      - data/train.csv
      - data/test.csv
      - data/processed/

  model_building:
    cmd: python src/model_building.py
    deps:
      - src/model_building.py
      - data/processed/
      - params.yaml
    params:
      - model.type
      - model.params
      - model.save_path
    outs:
      - models/model.pkl
      - models/metadata.yaml

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - src/model_evaluation.py
      - models/model.pkl
      - data/processed/X_test.npy
      - data/processed/y_test.npy
      - params.yaml
    params:
      - model_evaluation.metrics_save_path
      - model_evaluation.predictions_save_path
      - model_evaluation.evaluation_threshold
      - mlflow.tracking_uri
      - mlflow.experiment_name
    metrics:
      - reports/metrics.json
    outs:
      - reports/predictions.csv
      - reports/experiment_info.json
      - reports/feature_importance.csv


  model_registry:
    cmd: python src/register_model.py
    deps:
      - src/register_model.py
      - reports/experiment_info.json
      - params.yaml
    params:
      - mlflow.tracking_uri
      - mlflow.model_name
    outs:
      - reports/registry_info.json